# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import index_pb2 as index__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in index_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexStub(object):
    """O serviço principal do Index
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.takeNext = channel.unary_unary(
                '/index.Index/takeNext',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.TakeNextResponse.FromString,
                _registered_method=True)
        self.putNew = channel.unary_unary(
                '/index.Index/putNew',
                request_serializer=index__pb2.PutNewRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AcknowledgeUrl = channel.unary_unary(
                '/index.Index/AcknowledgeUrl',
                request_serializer=index__pb2.AcknowledgeUrlRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.searchWord = channel.unary_unary(
                '/index.Index/searchWord',
                request_serializer=index__pb2.SearchWordRequest.SerializeToString,
                response_deserializer=index__pb2.SearchWordResponse.FromString,
                _registered_method=True)
        self.searchListPages = channel.unary_unary(
                '/index.Index/searchListPages',
                request_serializer=index__pb2.SearchListPagesRequest.SerializeToString,
                response_deserializer=index__pb2.SearchListPagesResponse.FromString,
                _registered_method=True)
        self.getStatistics = channel.unary_unary(
                '/index.Index/getStatistics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.StatisticsResponse.FromString,
                _registered_method=True)
        self.IndexPageData = channel.unary_unary(
                '/index.Index/IndexPageData',
                request_serializer=index__pb2.IndexRequest.SerializeToString,
                response_deserializer=index__pb2.IndexWordsResponse.FromString,
                _registered_method=True)
        self.AddPageLinks = channel.unary_unary(
                '/index.Index/AddPageLinks',
                request_serializer=index__pb2.AddLinksRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterBarrel = channel.unary_unary(
                '/index.Index/RegisterBarrel',
                request_serializer=index__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/index.Index/SendHeartbeat',
                request_serializer=index__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActiveBarrels = channel.unary_unary(
                '/index.Index/GetActiveBarrels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.BarrelListResponse.FromString,
                _registered_method=True)
        self.GetFullState = channel.unary_stream(
                '/index.Index/GetFullState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.StateChunk.FromString,
                _registered_method=True)


class IndexServicer(object):
    """O serviço principal do Index
    """

    def takeNext(self, request, context):
        """--- MÉTODOS DA FILA (Chamados na Gateway) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def putNew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeUrl(self, request, context):
        """NOVO: Confirmação de processamento (Lease)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchWord(self, request, context):
        """--- MÉTODOS DE LEITURA (Chamados na Gateway -> Barrel) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchListPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexPageData(self, request, context):
        """NOVO: RPC de escrita de página (substitui indexWords)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPageLinks(self, request, context):
        """NOVO: RPC de escrita de links (substitui addLinkToUrl)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterBarrel(self, request, context):
        """--- MÉTODOS DE SERVICE DISCOVERY (Gateway e Barrel) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveBarrels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullState(self, request, context):
        """--- MÉTODO DE SINCRONIZAÇÃO (Barrel -> Barrel) ---
        ALTERADO: Agora retorna um stream de chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'takeNext': grpc.unary_unary_rpc_method_handler(
                    servicer.takeNext,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.TakeNextResponse.SerializeToString,
            ),
            'putNew': grpc.unary_unary_rpc_method_handler(
                    servicer.putNew,
                    request_deserializer=index__pb2.PutNewRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AcknowledgeUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeUrl,
                    request_deserializer=index__pb2.AcknowledgeUrlRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'searchWord': grpc.unary_unary_rpc_method_handler(
                    servicer.searchWord,
                    request_deserializer=index__pb2.SearchWordRequest.FromString,
                    response_serializer=index__pb2.SearchWordResponse.SerializeToString,
            ),
            'searchListPages': grpc.unary_unary_rpc_method_handler(
                    servicer.searchListPages,
                    request_deserializer=index__pb2.SearchListPagesRequest.FromString,
                    response_serializer=index__pb2.SearchListPagesResponse.SerializeToString,
            ),
            'getStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.getStatistics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.StatisticsResponse.SerializeToString,
            ),
            'IndexPageData': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexPageData,
                    request_deserializer=index__pb2.IndexRequest.FromString,
                    response_serializer=index__pb2.IndexWordsResponse.SerializeToString,
            ),
            'AddPageLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPageLinks,
                    request_deserializer=index__pb2.AddLinksRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegisterBarrel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBarrel,
                    request_deserializer=index__pb2.HeartbeatRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=index__pb2.HeartbeatRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetActiveBarrels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveBarrels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.BarrelListResponse.SerializeToString,
            ),
            'GetFullState': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFullState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.StateChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'index.Index', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('index.Index', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Index(object):
    """O serviço principal do Index
    """

    @staticmethod
    def takeNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/takeNext',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.TakeNextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def putNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/putNew',
            index__pb2.PutNewRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/AcknowledgeUrl',
            index__pb2.AcknowledgeUrlRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/searchWord',
            index__pb2.SearchWordRequest.SerializeToString,
            index__pb2.SearchWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchListPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/searchListPages',
            index__pb2.SearchListPagesRequest.SerializeToString,
            index__pb2.SearchListPagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/getStatistics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.StatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexPageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/IndexPageData',
            index__pb2.IndexRequest.SerializeToString,
            index__pb2.IndexWordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPageLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/AddPageLinks',
            index__pb2.AddLinksRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterBarrel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/RegisterBarrel',
            index__pb2.HeartbeatRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/SendHeartbeat',
            index__pb2.HeartbeatRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveBarrels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/index.Index/GetActiveBarrels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.BarrelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/index.Index/GetFullState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.StateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
